### ISSUE TITLE
Everything dissapeared after installing

### ISSUE THREAD

**Issue by Blkzer0** [Eitenne/roxysploit#4]
yeah its weird, after i ran the install script, everything in the roxysploit dir is gone and the script will not start up with sudo. the installed looked fine and i didnt encounter much error except for the " No matching distribution found for" just as alphaaurigae experienced. I tried installing the packages manually with pip and still got the same error. I tested this on parrot os and ubuntu 17.10. Let me know how i can fix this.

**Comment by Eitenne** [comment]
The needed modules are already installed but i just added a bunch of used ones in the tool anyways incase if i missed anything but once its done everything will disapear and it will be in the /opt directory run 'sudo rsfc'
