### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by emans841** [Eitenne/roxysploit#5]
cant get to install it.kali linux 2018.kindly look into this

**Comment by kefkahacks** [comment]
kindly provide some kind of verbosity
regards

**Comment by emans841** [comment]
So im going to load all files now for you please wait...
mkdir: cannot create directory ‘/opt/roxysploit’: File exists
mv: cannot move 'banners' to '/opt/roxysploit/banners': Directory not empty
mv: cannot move 'core' to '/opt/roxysploit/core': Directory not empty
mv: cannot move 'modules' to '/opt/roxysploit/modules': Directory not empty
mv: cannot move 'plugins' to '/opt/roxysploit/plugins': Directory not empty
mv: cannot move 'storage' to '/opt/roxysploit/storage': Directory not empty
mkdir: cannot create directory ‘/opt/roxysploit/storage/logs’: File exists

**Comment by emans841** [comment]
rom cffi callback <function _verify_callback at 0xb6883bc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement logging (from versions: )
No matching distribution found for logging

**Comment by emans841** [comment]
No matching distribution found for pysmb
Collecting threading
From cffi callback <function _verify_callback at 0xb6859bc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement threading (from versions: )
No matching distribution found for threading
Collecting socket
From cffi callback <function _verify_callback at 0xb685fbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement socket (from versions: )
No matching distribution found for socket
Collecting socks
From cffi callback <function _verify_callback at 0xb687e684>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement socks (from versions: )
No matching distribution found for socks
Collecting zipfile
From cffi callback <function _verify_callback at 0xb689abc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement zipfile (from versions: )
No matching distribution found for zipfile
Collecting shutil
From cffi callback <function _verify_callback at 0xb6812bc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement shutil (from versions: )
No matching distribution found for shutil
Collecting io
From cffi callback <function _verify_callback at 0xb68bccdc>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement io (from versions: )
No matching distribution found for io
Collecting struct
From cffi callback <function _verify_callback at 0xb682fbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement struct (from versions: )
No matching distribution found for struct
Collecting re
From cffi callback <function _verify_callback at 0xb68b6cdc>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement re (from versions: )
No matching distribution found for re
Collecting optparse
From cffi callback <function _verify_callback at 0xb68b9bc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement optparse (from versions: )
No matching distribution found for optparse
Collecting binascii
From cffi callback <function _verify_callback at 0xb6840bc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement binascii (from versions: )
No matching distribution found for binascii
Collecting base64
From cffi callback <function _verify_callback at 0xb680abc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement base64 (from versions: )
No matching distribution found for base64
Requirement already satisfied: urllib2 in /usr/local/lib/python2.7/dist-packages
Collecting urllib
From cffi callback <function _verify_callback at 0xb67edbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement urllib (from versions: )
No matching distribution found for urllib
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages
Collecting commands
From cffi callback <function _verify_callback at 0xb68dcbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement commands (from versions: )
No matching distribution found for commands
Requirement already satisfied: paramiko in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: cryptography>=1.1 in /usr/local/lib/python2.7/dist-packages (from paramiko)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7->cryptography>=1.1->paramiko)
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages
Collecting whois
From cffi callback <function _verify_callback at 0xb68c3684>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement whois (from versions: )
No matching distribution found for whois
Collecting rlcompleter
From cffi callback <function _verify_callback at 0xb685fbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement rlcompleter (from versions: )
No matching distribution found for rlcompleter
Collecting readline
From cffi callback <function _verify_callback at 0xb685dbc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement readline (from versions: )
No matching distribution found for readline
Requirement already satisfied: terminaltables in /usr/local/lib/python2.7/dist-packages
Collecting platform
From cffi callback <function _verify_callback at 0xb685abc4>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement platform (from versions: )
No matching distribution found for platform

**Comment by emans841** [comment]
kindly help me look into that

**Comment by Eitenne** [comment]
Hi, im going to work on a more supportive installer soon but remove the existing roxysploit and try to reinstall also the python modules are already installed.

> rm -rf /opt/roxysploit

**Comment by Eitenne** [comment]
Hi quick update i remade the installer as mentioned, it should be fully working now :)
