### ISSUE TITLE
Missing hello.plugin

### ISSUE THREAD

**Issue by suduma** [Eitenne/roxysploit#6]
Fresh git install on kali linux and then used update.py to reinstall and issue persist.

[*] Preparing environment... 100
[?] Creating logfile: /opt/roxysploit/storage/logs/27-02-2018-23:03:56.log
[*] Retargetting Session
[+] Default Target IP Address [0]: 
[?] Initializing Global State
[+] Set TargetIp => 0
[+] Loaded plugins => 34
[+] Detected Version => 4.9.3

rsf > plugin
python: can't open file 'plugins/hello.plugin': [Errno 2] No such file or directory

Logfile Contents:
INFO:root:plugin
INFO:root:exit

/opt/roxysploit/storage/plugins.loaded is an empty file

**Comment by Eitenne** [comment]
Ah yes when trying to reorganise the plugins i forgot about the hello.plugin i will need to fix or disable that option for now everything else should work :)

**Comment by Eitenne** [comment]
if you run "rsfupdate" it should be fixed now
