### ISSUE TITLE
OSX port

### ISSUE THREAD

**Issue by VaXe-Hunter** [Eitenne/roxysploit#7]
Hi, I was wondering if you managed to execute the framework on mac. When I try and run it, it says it cannot create a log file and spits out this error. What should I try and do to port it to mac?
<img width="743" alt="file1" src="https://user-images.githubusercontent.com/6174153/37310692-fa25b604-2601-11e8-9593-02ff19d9a196.png">

**Comment by Eitenne** [comment]
For mac the installer will not work but for log errors the logs directory does not exist so run 'mkdir storage/logs'
